# Generated by Django 3.2.3 on 2021-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account_app', '0002_auto_20210527_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Username'),
        ),
    ]
